app:
  allowBets: true

server:
  port: 9090
  error:
    include-stacktrace: never
spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  application:
    name: Poolio
  datasource:
    password: golf9c
    url: jdbc:postgresql://localhost:5432/poolio
    username: mike
#      password: golf9c
#      url: jdbc:postgresql://poolio.local:5432/poolio
#      username: mike
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mustache:
    check-template-location: false
  sql:
    init:
      mode: never
vaadin:
  allowed-packages: com.vaadin,org.vaadin,nm.poolio
  frontend:
    hotdeploy: true
  launch-browser: true

logging:
  level:
    root: INFO
    org.atmosphere: WARN
    nm: DEBUG
    net.ttddyy.dsproxy.listener: ERROR
  pattern:
    console: "%date %green(%level) %blue([%thread]) %cyan(%logger{30}:%line) %magenta(%mdc)  %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: '*'
