app:
  allowBets: false

server:
  port:  9090

spring:
  datasource:
    password: golf9c
    url: jdbc:postgresql://poolio.local:5432/poolio
    username: mike
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO
  file:
    name: poolio.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %mdc %logger{36}.%M - %msg%n"
    console:
management:
  endpoints:
    enabled-by-default: false